### ISSUE TITLE
How to get translation vector

### ISSUE THREAD

**Issue by Vampire-Vx** [swook/faze_preprocess#1]
https://github.com/swook/faze_preprocess/blob/5c33caaa1bc271a8d6aad21837e334108f293683/create_hdf_files_for_faze.py#L175
Here shows a translation vector, which seems to be the translation vector between camera origin and head position in 3D camera coordinate. May I ask how do you get these tranlation vectors ? Because most of the 3D facial landmarks result points are relative coordinates ?
I can understand that a rotation matrix can be determinated using a face landmarks detection model, and a sfm face model is used to refine the rotation matrix, but how can we get a translation vector without absolute scale?

**Comment by swook** [comment]
We calculate the translation vector based on PnP-based 6-DoF head pose estimation against the Surrey Face Model (mean). This requires face detection, 2D facial landmarks detection, and camera intrinsic parameters as pre-requisites.

The PnP step determines both the rotation (3-DoF) and translation (3-DoF) based on a 3D face model defined in millimetre units. You can find the relevant code at https://bitbucket.org/swook/preprocess4gaze/src/2ec8f7bf7b83a81e6a795c6002272058dab0e950/src/head.py#lines-123

Please find the relevant paper text in our Appendix A.1 of our paper at: https://arxiv.org/pdf/1905.01941.pdf

**Comment by Vampire-Vx** [comment]
Thanks a lot for details.
