### ISSUE TITLE
Can't download MPIIFaceGaze_supplementary.h5 and GazeCapture_supplementary.h5 now

### ISSUE THREAD

**Issue by AtalsZem** [swook/faze_preprocess#11]
![image](https://github.com/swook/faze_preprocess/assets/86402580/aa1b9ef6-0c94-414f-86c1-2a9965635fee)

**Comment by swook** [comment]
This is now resolved with [4e76176](https://github.com/swook/faze_preprocess/commit/4e76176ecccc127f3fa5c03acfdb7f162ddd612d) - thanks for letting me know about the broken link!

**Comment by AtalsZem** [comment]
> This is now resolved with [4e76176](https://github.com/swook/faze_preprocess/commit/4e76176ecccc127f3fa5c03acfdb7f162ddd612d) - thanks for letting me know about the broken link!

Thanks a lot!
