### ISSUE TITLE
Direction vector to Euler angles 

### ISSUE THREAD

**Issue by Vampire-Vx** [swook/faze_preprocess#2]
https://github.com/swook/faze_preprocess/blob/5c33caaa1bc271a8d6aad21837e334108f293683/create_hdf_files_for_faze.py#L97
Line 97 here, the vecor[:,1] is the normalized y coordinate. Actually it is a pictch angle? You write a yaw angle in the comment

**Comment by swook** [comment]
Thanks for catching this out. I've fixed the comment in 16d1997
