### ISSUE TITLE
r

### ISSUE THREAD

**Issue by nhathoang0110** [swook/faze_preprocess#3]
I am running in server and i have error:
Processing MPIIGaze/p00
Distortion map parameters updated.
fx: 994.74, fy: 998.17, cx: 624.66, cy: 364.09
: cannot connect to X server 
Please help me,what is code i have to delete ? thanks

**Comment by swook** [comment]
Hi there, if you comment out the code block at https://github.com/swook/faze_preprocess/blob/master/create_hdf_files_for_faze.py#L222 does it work?

Basically, the problem is caused because the `cv.imshow` command requires a display server.
