### ISSUE TITLE
full-image preprocess

### ISSUE THREAD

**Issue by yongwuML** [swook/faze_preprocess#5]
How do I preprocess a full-image, not two eyes. Thank you.

**Comment by swook** [comment]
Hi, thanks for your interest in our research.

We had to make a few small changes to do this for our latest project (ST-ED),
and the updated script is available at https://github.com/swook/faze_preprocess/blob/master/create_hdf_files_for_sted.py

Please look at the changes (with respect to the original script) to see how we achieved this.
Also, please note that there is a new dependency in `requirements.txt` and you must run `grab_prerequisites.bash` again.
